In [1]:
#!pip install --upgrade "jax[cpu]"
#!pip install optax
#!pip install IngeoML

In [2]:
import sys
print(sys.version)

3.11.7 (main, Dec 15 2023, 12:09:04) [Clang 14.0.6 ]


In [3]:
import os
n_cores = os.cpu_count()
print(f"Número de núcleos de CPU disponibles: {n_cores}")


Número de núcleos de CPU disponibles: 4


In [4]:
from IngeoML import StatisticSamples
from sklearn.metrics import accuracy_score,recall_score
import numpy as np

In [5]:
# ahora verificando las muestras
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
statistic2 = StatisticSamples(num_samples=10, statistic=np.std)
print(statistic2(empirical_distribution))
print("Muestras de statistic2 (std) \n",statistic2._samples)

[3.6 3.  4.4 3.4 4.  4.4 3.2 3.4 4.  3. ]
Muestras de statistic (mean) 
 [[4 0 3 2 1]
 [0 3 0 0 4]
 [2 2 4 1 1]
 [2 3 3 4 4]
 [2 1 0 1 4]
 [2 0 2 2 1]
 [2 0 3 4 3]
 [1 1 3 0 1]
 [1 1 0 4 2]
 [1 0 3 3 4]]
[1.16619038 0.8        0.63245553 0.74833148 0.8        0.9797959
 1.09544512 0.48989795 0.48989795 0.8       ]
Muestras de statistic2 (std) 
 [[1 3 3 0 2]
 [4 4 1 1 3]
 [0 0 0 3 1]
 [0 3 0 4 1]
 [0 0 0 2 0]
 [1 1 1 2 3]
 [2 4 1 3 2]
 [0 4 0 4 4]
 [4 2 2 2 4]
 [2 1 2 2 0]]


In [6]:

# ahora verificando las muestras
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
statistic2 = StatisticSamples(num_samples=10, statistic=np.mean)
print(statistic2(empirical_distribution))
print("Muestras de statistic2 (mean2) \n",statistic2._samples)

[3.2 4.2 4.  4.  4.4 3.8 3.6 4.4 3.6 3.6]
Muestras de statistic (mean) 
 [[3 0 0 2 0]
 [2 1 2 4 0]
 [4 2 4 1 0]
 [1 4 2 0 4]
 [1 1 2 2 4]
 [4 0 0 4 2]
 [0 4 2 3 4]
 [1 4 2 2 1]
 [2 4 0 0 0]
 [0 1 2 4 3]]
[3.6 3.2 3.6 3.6 3.4 3.4 3.4 3.6 3.8 3.6]
Muestras de statistic2 (mean2) 
 [[4 0 1 4 0]
 [3 2 0 3 1]
 [0 0 4 1 1]
 [0 0 1 1 4]
 [4 4 3 1 0]
 [1 2 3 3 1]
 [3 1 0 1 4]
 [4 2 1 0 3]
 [0 3 2 4 2]
 [2 1 3 4 0]]


In [7]:
labels = np.r_[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]
pred   = np.r_[[0, 0, 1, 0, 0, 1, 1, 1, 0, 1]]
print(accuracy_score(labels, pred))
acc = StatisticSamples(num_samples=10, statistic=accuracy_score)
acc(labels, pred)
print("Muestras de acc \n",acc._samples)
print(recall_score(labels, pred,zero_division =0.0))
rec = StatisticSamples(num_samples=10, statistic=recall_score)
rec(labels, pred)
print("Muestras de recall \n",rec._samples)

0.8
Muestras de acc 
 [[7 1 1 7 6 8 3 1 1 2]
 [3 5 0 0 8 3 7 9 6 3]
 [3 6 8 9 2 2 1 8 2 6]
 [7 4 8 5 7 9 4 0 9 2]
 [0 7 3 7 0 7 1 1 3 6]
 [0 0 9 5 2 2 8 3 3 3]
 [3 1 7 7 6 9 5 5 6 7]
 [0 2 4 1 0 8 3 7 3 0]
 [0 2 3 0 0 4 7 3 4 8]
 [0 4 7 5 8 9 2 0 9 7]]
0.8
Muestras de recall 
 [[8 9 9 3 1 1 0 7 2 8]
 [7 3 0 9 0 8 3 6 4 4]
 [8 5 0 9 8 0 6 2 2 5]
 [5 4 7 7 4 0 7 8 0 8]
 [1 7 2 7 9 1 7 2 0 0]
 [1 8 2 6 9 9 5 0 4 8]
 [4 3 8 3 9 3 9 8 1 7]
 [6 2 4 3 7 3 3 6 5 7]
 [7 8 5 2 5 2 3 1 9 2]
 [2 9 7 1 1 9 5 0 1 3]]


In [8]:
print(labels.shape)
print(pred.shape)

(10,)
(10,)
