In [57]:

#!pip install --upgrade "jax[cpu]"

In [58]:
#!pip install optax

In [59]:
#!pip install IngeoML

In [60]:
import sys
print(sys.version)

3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]


In [61]:
import os
n_cores = os.cpu_count()
print(f"Número de núcleos de CPU disponibles: {n_cores}")


Número de núcleos de CPU disponibles: 8


In [91]:
from IngeoML import StatisticSamples
from sklearn.metrics import accuracy_score,recall_score
import numpy as np

In [88]:
# ahora verificando las muestras
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
statistic2 = StatisticSamples(num_samples=10, statistic=np.std)
print(statistic2(empirical_distribution))
print("Muestras de statistic2 (std) \n",statistic2._samples)

[3.8 4.  3.8 3.8 2.4 3.6 3.4 3.6 3.2 4. ]
Muestras de statistic (mean) 
 [[4 4 1 2 3]
 [1 1 2 0 4]
 [1 1 0 1 1]
 [0 4 2 2 3]
 [3 3 1 3 3]
 [3 2 0 2 0]
 [0 0 4 0 1]
 [4 2 3 0 4]
 [0 3 4 0 4]
 [4 2 4 0 4]]
[1.0198039  0.89442719 0.8        1.16619038 1.356466   1.0198039
 0.89442719 1.16619038 0.8        1.0198039 ]
Muestras de statistic2 (std) 
 [[0 2 3 1 1]
 [2 0 0 2 4]
 [1 4 1 3 0]
 [3 3 2 0 1]
 [3 1 3 2 2]
 [3 1 0 0 2]
 [2 0 1 2 0]
 [3 2 4 3 0]
 [4 0 2 2 2]
 [0 2 3 1 4]]


In [97]:

# ahora verificando las muestras
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
statistic2 = StatisticSamples(num_samples=10, statistic=np.mean)
print(statistic2(empirical_distribution))
print("Muestras de statistic2 (mean2) \n",statistic2._samples)

[3.4 4.  3.4 4.6 4.2 3.2 2.8 3.8 3.6 3.6]
Muestras de statistic (mean) 
 [[1 1 0 4 3]
 [4 2 0 2 0]
 [4 1 3 0 4]
 [2 2 2 4 4]
 [4 4 2 4 1]
 [3 3 2 0 1]
 [4 3 4 3 3]
 [0 2 0 1 4]
 [4 1 1 0 0]
 [3 4 2 0 4]]
[3.  3.2 3.2 3.8 3.2 4.  3.6 3.6 2.6 3.6]
Muestras de statistic2 (mean2) 
 [[3 0 4 0 0]
 [2 0 3 3 1]
 [3 3 3 2 2]
 [1 1 4 0 4]
 [0 0 1 3 4]
 [1 4 2 3 2]
 [4 3 4 0 2]
 [1 1 3 0 2]
 [1 0 3 3 3]
 [4 3 0 4 2]]


In [95]:
labels = np.r_[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]
pred   = np.r_[[0, 0, 1, 0, 0, 1, 1, 1, 0, 1]]
print(accuracy_score(labels, pred))
acc = StatisticSamples(num_samples=10, statistic=accuracy_score)
acc(labels, pred)
print("Muestras de acc \n",acc._samples)
print(recall_score(labels, pred,zero_division =0.0))
rec = StatisticSamples(num_samples=10, statistic=recall_score)
rec(labels, pred)
print("Muestras de recall \n",rec._samples)

0.8
Muestras de acc 
 [[8 9 5 8 7 7 5 7 5 5]
 [8 8 1 1 3 9 5 1 3 3]
 [4 3 2 4 6 2 1 1 3 3]
 [5 2 2 1 0 8 3 3 6 3]
 [0 3 6 8 0 4 7 1 7 6]
 [7 6 0 0 4 6 5 6 0 0]
 [0 3 3 2 4 1 3 0 5 5]
 [5 1 0 3 4 0 1 4 4 5]
 [2 5 6 7 7 7 1 8 7 1]
 [2 9 4 3 3 8 7 6 5 8]]
0.8
Muestras de recall 
 [[2 0 4 5 2 5 1 2 8 5]
 [9 7 5 7 3 7 5 9 0 0]
 [6 0 9 1 6 4 5 6 4 5]
 [1 0 4 4 3 1 4 4 0 6]
 [1 7 9 2 4 1 0 8 2 2]
 [1 1 7 8 3 2 8 8 0 4]
 [0 8 7 6 7 6 3 7 9 9]
 [6 0 9 6 7 4 1 9 6 0]
 [4 5 0 7 9 1 9 9 9 5]
 [8 2 2 7 5 2 9 2 8 1]]


In [96]:
print(labels.shape)
print(pred.shape)

(10,)
(10,)
