# Código para entender las funcionalidad de *IngeoML*

In [30]:
# Bloque de código para instalar las bibliotecas necesarias para correr IngeoML
#!pip install --upgrade "jax[cpu]"
#!pip install optax
!pip install IngeoML

In [14]:
# Verificar que versión de python se está usando.
import sys
print(sys.version)

3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]


In [15]:
# Cuántos núcleos disponibles hay en el CPU
import os
n_cores = os.cpu_count()
print(f"Número de núcleos de CPU disponibles: {n_cores}")


Número de núcleos de CPU disponibles: 4


In [31]:
from IngeoML import StatisticSamples
from sklearn.metrics import accuracy_score,recall_score
import numpy as np

In [32]:
# se obtiene la distribución muestral de la la media y la desvición estándar
# de 10 muestras bootstrap de una población de cinco datos
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
statistic2 = StatisticSamples(num_samples=10, statistic=np.std)
print(statistic2(empirical_distribution))
print("Muestras de statistic2 (std) \n",statistic2._samples)
# en este caso se usand dos objetos-funciones "statistic" y "statistic2"

[3.6 4.2 3.8 3.2 2.8 2.8 4.  3.  3.4 3.8]
Muestras de statistic (mean) 
 [[2 4 0 3 1]
 [2 2 1 1 0]
 [2 3 4 1 1]
 [3 1 3 2 0]
 [0 4 0 3 3]
 [3 4 3 1 3]
 [0 1 2 4 4]
 [4 4 3 0 3]
 [0 0 3 1 2]
 [3 2 2 0 4]]
[2.4 4.2 4.2 3.8 3.8 3.6 4.  3.4 3.2 3. ]
Muestras de statistic (mean) 
 [[3 0 3 3 0]
 [4 0 2 2 4]
 [1 2 1 4 4]
 [1 4 1 0 1]
 [3 1 2 4 1]
 [0 3 4 4 2]
 [4 4 4 2 0]
 [2 4 3 4 3]
 [4 4 0 0 3]
 [2 4 3 3 3]]
[0.4        0.8        1.0198039  1.16619038 0.74833148 0.89442719
 1.16619038 0.74833148 1.2        1.0198039 ]
Muestras de statistic2 (std) 
 [[0 4 4 4 1]
 [0 3 4 3 3]
 [4 2 0 4 3]
 [1 3 3 2 0]
 [4 2 2 1 0]
 [2 0 1 0 2]
 [3 4 2 0 2]
 [0 1 1 0 3]
 [2 3 4 1 3]
 [4 3 2 4 0]]


Como se puede ver, las muestras son diferentes en cada llamado, eso dificulta poder hacer bootstrap para diferentes estadísticos y/o métricas

In [10]:

# se repite el experimento
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
statistic2 = StatisticSamples(num_samples=10, statistic=np.mean)
print(statistic2(empirical_distribution))
print("Muestras de statistic2 (mean2) \n",statistic2._samples)
# en este caso se utilizó la misma distribución "empirical_distribution"

[4.  3.6 3.4 3.8 4.  3.2 3.4 4.2 3.8 3.8]
Muestras de statistic (mean) 
 [[4 4 2 0 4]
 [0 2 4 1 3]
 [1 0 1 3 1]
 [4 0 4 1 1]
 [2 1 2 4 3]
 [0 2 0 3 0]
 [4 0 0 4 0]
 [1 1 2 4 4]
 [2 4 3 4 4]
 [2 4 2 3 0]]
[3.6 4.  4.  2.8 4.  4.  3.8 4.  3.2 4. ]
Muestras de statistic2 (mean2) 
 [[2 4 3 0 1]
 [3 4 2 4 2]
 [1 2 3 2 1]
 [0 3 3 1 0]
 [1 1 1 1 1]
 [4 2 3 4 2]
 [3 4 2 0 2]
 [2 0 4 4 1]
 [0 0 0 2 3]
 [1 4 1 0 2]]


In [11]:

# se repite el experimento
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
print(statistic(empirical_distribution))
print("Muestras de statistic (mean) \n",statistic._samples)
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
print(statistic(empirical_distribution))
print("Muestras de statistic2 (mean2) \n",statistic._samples)
# en este caso se utilizó la misma distribución "empirical_distribution" 
# y el mismo nombre de funcion-objeto "statistic" y sin embargo las 
# muestras son distintas

[3.6 3.4 3.6 3.  3.8 3.8 3.8 4.2 3.4 3.2]
Muestras de statistic (mean) 
 [[4 1 4 1 3]
 [4 4 1 3 0]
 [1 3 2 1 0]
 [3 2 0 3 0]
 [2 0 2 1 3]
 [4 2 1 0 0]
 [0 0 2 4 4]
 [4 0 4 2 2]
 [0 0 1 4 0]
 [0 0 3 2 0]]
[3.6 3.2 3.6 3.2 3.8 3.4 3.8 3.2 3.4 3.6]
Muestras de statistic2 (mean2) 
 [[4 4 1 1 3]
 [0 0 3 1 1]
 [4 3 1 1 4]
 [0 0 4 3 1]
 [4 4 1 3 2]
 [1 0 1 3 4]
 [2 0 4 2 3]
 [1 3 3 1 4]
 [3 1 0 2 0]
 [3 4 2 1 0]]


In [12]:
# se repite el ejemplo con métricas de desempeño y nuevamente 
# las muestras son distintas
labels = np.r_[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]
pred   = np.r_[[0, 0, 1, 0, 0, 1, 1, 1, 0, 1]]
print(accuracy_score(labels, pred))
acc = StatisticSamples(num_samples=10, statistic=accuracy_score)
acc(labels, pred)
print("Muestras de acc \n",acc._samples)
print(recall_score(labels, pred,zero_division =0.0))
rec = StatisticSamples(num_samples=10, statistic=recall_score)
rec(labels, pred)
print("Muestras de recall \n",rec._samples)

0.8
Muestras de acc 
 [[6 7 1 2 6 8 9 3 4 1]
 [9 7 7 4 0 8 1 1 1 6]
 [7 2 3 7 4 7 6 7 1 6]
 [6 1 7 0 8 7 1 9 4 3]
 [5 2 8 7 8 8 7 0 2 2]
 [7 1 7 6 3 2 6 2 9 7]
 [4 1 9 1 6 2 1 3 6 9]
 [7 7 9 8 8 9 4 1 0 7]
 [4 1 7 6 8 5 7 0 6 2]
 [0 5 0 4 8 0 1 3 9 6]]
0.8
Muestras de recall 
 [[8 9 1 3 8 5 1 8 6 1]
 [1 6 8 0 3 1 1 5 6 1]
 [0 5 3 5 8 9 8 7 6 2]
 [8 1 2 9 1 2 2 5 3 1]
 [3 0 9 2 1 1 5 8 1 7]
 [4 3 0 1 1 0 1 1 4 4]
 [1 4 3 5 2 7 7 9 5 8]
 [8 0 7 5 1 1 3 1 2 5]
 [5 6 9 6 0 5 6 1 1 4]
 [3 5 5 9 1 1 7 7 6 9]]


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
