In [ ]:

#!pip install --upgrade "jax[cpu]"

In [ ]:
#!pip install optax

In [ ]:
#!pip install IngeoML

In [53]:
import os
n_cores = os.cpu_count()
print(f"Número de núcleos de CPU disponibles: {n_cores}")


Número de núcleos de CPU disponibles: 8


In [18]:
import time


In [2]:
from IngeoML import StatisticSamples
from sklearn.metrics import accuracy_score
import numpy as np

In [15]:
# versión original
statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
statistic(empirical_distribution)
labels = np.r_[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]
pred   = np.r_[[0, 0, 1, 0, 0, 1, 1, 1, 0, 1]]
print(accuracy_score(labels, pred))
acc = StatisticSamples(num_samples=10000, statistic=accuracy_score)
acc(labels, pred)

0.8


array([1. , 0.8, 0.9, ..., 0.6, 0.5, 0.9])

In [8]:
print(labels.shape)
print(pred.shape)

(10,)
(10,)


In [51]:

statistic = StatisticSamples(num_samples=10, statistic=np.mean)
empirical_distribution = np.r_[[3, 4, 5, 2, 4]]
statistic(empirical_distribution)
labels = np.r_[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]
predicciones_matriz = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 0, 1],
                                [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
                                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0]])
predicciones_matriz = predicciones_matriz.T
print(labels.shape)
print(predicciones_matriz.shape)

start_time = time.time()


for i in range(predicciones_matriz.shape[1]):
    predicciones_modelo = predicciones_matriz[:, i]
    precisión_modelo = accuracy_score(labels, predicciones_modelo)
    print(f"Precisión del Modelo {i + 1}: {precisión_modelo}")
    acc = StatisticSamples(num_samples=10000, statistic=accuracy_score, n_jobs = -1)
    acc(labels, pred)
    

end_time = time.time()
print(f"Tiempo de ejecución: {end_time - start_time} segundos")


(10,)
(10, 3)
Precisión del Modelo 1: 0.8
Precisión del Modelo 2: 0.8
Precisión del Modelo 3: 0.9
Tiempo de ejecución: 2.6109979152679443 segundos


In [52]:
# arreglo por renglón.
# Cada renglón es una competidor
labels = np.r_[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]
predicciones_matriz = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 0, 1],
                                [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
                                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0]])
resultado = np.array([accuracy_score(predicciones_matriz[i, :], labels) for i in range(predicciones_matriz.shape[0])])
resultado

array([0.8, 0.8, 0.9])

In [43]:
start_time = time.time()
acc = StatisticSamples(num_samples=10000, statistic=accuracy_score, n_jobs = -1)
np.array([acc(labels,predicciones_matriz[i, :]) for i in range(predicciones_matriz.shape[0])]).T
end_time = time.time()
print(f"Tiempo de ejecución: {end_time - start_time} segundos")


Tiempo de ejecución: 2.5689940452575684 segundos


In [13]:
# arreglo por columna.
# Cada columna es una competidor
predicciones_matriz2 = predicciones_matriz.T
np.array([accuracy_score(predicciones_matriz2[:, i], labels) for i in range(predicciones_matriz2.shape[1])])

array([0.8, 0.8, 0.9])

In [53]:
acc = StatisticSamples(num_samples=100, statistic=accuracy_score)
distMuestralAcc = np.array([acc(labels,predicciones_matriz2[:, i]) for i in range(predicciones_matriz2.shape[1])]).T
print(distMuestralAcc)
print(np.mean(distMuestralAcc,axis=0))

[[0.6 0.9 0.7]
 [0.9 0.7 0.6]
 [0.7 0.9 1. ]
 [0.9 1.  1. ]
 [0.9 0.9 0.9]
 [0.8 0.3 0.9]
 [0.8 1.  0.8]
 [0.7 0.8 0.9]
 [0.8 0.6 0.9]
 [0.8 0.9 0.8]
 [0.9 0.7 0.9]
 [0.9 0.8 0.8]
 [0.7 0.9 1. ]
 [0.9 0.8 0.7]
 [0.6 0.8 0.8]
 [0.9 0.9 0.9]
 [0.9 0.6 0.9]
 [1.  0.7 0.9]
 [0.9 0.7 0.8]
 [0.7 0.9 1. ]
 [0.7 0.8 0.9]
 [1.  0.8 0.9]
 [0.7 0.7 1. ]
 [0.5 0.7 0.9]
 [0.8 0.9 1. ]
 [0.8 0.7 1. ]
 [0.8 1.  0.7]
 [0.8 1.  1. ]
 [0.8 0.9 1. ]
 [0.8 0.7 0.9]
 [0.8 0.9 0.9]
 [0.8 0.9 0.9]
 [1.  0.9 1. ]
 [0.8 0.8 0.9]
 [0.9 0.6 0.9]
 [0.8 0.9 1. ]
 [0.8 0.8 1. ]
 [0.8 0.6 1. ]
 [0.8 0.7 0.6]
 [0.7 0.7 0.8]
 [0.5 0.7 0.9]
 [0.8 0.9 1. ]
 [0.9 0.8 1. ]
 [0.7 0.5 0.8]
 [0.9 0.7 1. ]
 [0.7 0.9 1. ]
 [0.9 0.6 0.9]
 [0.9 0.7 1. ]
 [0.7 0.7 0.9]
 [0.9 0.8 0.9]
 [0.6 0.6 1. ]
 [0.7 0.7 0.9]
 [0.9 0.8 0.9]
 [0.9 0.8 1. ]
 [0.9 0.8 1. ]
 [0.8 0.9 0.8]
 [0.7 0.9 0.9]
 [0.9 0.5 1. ]
 [0.8 0.8 1. ]
 [1.  0.8 1. ]
 [0.9 0.9 0.9]
 [0.8 0.8 1. ]
 [0.8 0.9 0.9]
 [0.9 1.  1. ]
 [1.  0.9 0.8]
 [0.8 0.9 0.8]
 [0.9 0.8 